// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserManagementSystem.Data;

namespace UserManagementSystem.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    [Migration("20220524001403_updatedSeedData2")]
    partial class updatedSeedData2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("UserManagementSystem.Data.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("UserManagementSystem.Data.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Admin",
                            Description = "Admin opis"
                        },
                        new
                        {
                            Id = 2,
                            Code = "User",
                            Description = "User opis"
                        });
                });

            modelBuilder.Entity("UserManagementSystem.Data.Models.UserPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersPermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermissionId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            PermissionId = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("UserManagementSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StatusIsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4cae5d23-f61f-4cdc-9c0d-c47fe3dd1fcb",
                            Email = "marko@marko1.com",
                            EmailConfirmed = true,
                            FirstName = "Administrator",
                            LastName = "Markovic",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            StatusIsActive = true,
                            TwoFactorEnabled = false,
                            UserName = "marko@marko1.com"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0b3d9885-0981-4466-83b3-21625a28183a",
                            Email = "marko@marko2.com",
                            EmailConfirmed = true,
                            FirstName = "Mark",
                            LastName = "Markovic",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            StatusIsActive = true,
                            TwoFactorEnabled = false,
                            UserName = "marko@marko2.com"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c50a8286-e23e-4e97-8ae1-d4fbe60db6af",
                            Email = "marko@mar3ko.com",
                            EmailConfirmed = true,
                            FirstName = "Ivan",
                            LastName = "Markovic",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            StatusIsActive = true,
                            TwoFactorEnabled = false,
                            UserName = "marko@mar3ko.com"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4d06e0ac-6b5a-4c3b-8336-f970cde2b520",
                            Email = "marko@mark4o.com",
                            EmailConfirmed = true,
                            FirstName = "Jovan",
                            LastName = "Markovic",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            StatusIsActive = true,
                            TwoFactorEnabled = false,
                            UserName = "marko@mark4o.com"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4be6cb4a-ab1b-4903-9482-17137158fdea",
                            Email = "marko@marko4.com",
                            EmailConfirmed = true,
                            FirstName = "Mirko",
                            LastName = "Markovic",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            StatusIsActive = true,
                            TwoFactorEnabled = false,
                            UserName = "marko@marko4.com"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e61f16f6-97e3-425f-b559-389110baa064",
                            Email = "marko@m6arko.com",
                            EmailConfirmed = true,
                            FirstName = "Slavko",
                            LastName = "Markovic",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            StatusIsActive = true,
                            TwoFactorEnabled = false,
                            UserName = "marko@m6arko.com"
                        },
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ffbf1e79-b903-4fa8-a53e-9211eb6290ea",
                            Email = "marko@ma6rko.com",
                            EmailConfirmed = true,
                            FirstName = "Simo",
                            LastName = "Markovic",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            StatusIsActive = true,
                            TwoFactorEnabled = false,
                            UserName = "marko@ma6rko.com"
                        },
                        new
                        {
                            Id = 8,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b3c81961-58b0-43d4-a5dc-db8cebff4183",
                            Email = "marko@mar6ko.com",
                            EmailConfirmed = true,
                            FirstName = "Luka",
                            LastName = "Markovic",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            StatusIsActive = true,
                            TwoFactorEnabled = false,
                            UserName = "marko@mar6ko.com"
                        },
                        new
                        {
                            Id = 9,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "20dbffd8-fdf7-4188-8067-7d2432780f48",
                            Email = "marko@mark6o.com",
                            EmailConfirmed = true,
                            FirstName = "Ante",
                            LastName = "Markovic",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            StatusIsActive = true,
                            TwoFactorEnabled = false,
                            UserName = "arko@mark6o.com"
                        },
                        new
                        {
                            Id = 10,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "83b7e864-97b9-4058-90f8-3eeb545ce3d3",
                            Email = "marko@marko6.com",
                            EmailConfirmed = true,
                            FirstName = "Filip",
                            LastName = "Markovic",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            StatusIsActive = true,
                            TwoFactorEnabled = false,
                            UserName = "marko@marko6.com"
                        },
                        new
                        {
                            Id = 11,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "69646b25-50cb-482e-82ec-526637333a57",
                            Email = "marko@m7arko.com",
                            EmailConfirmed = true,
                            FirstName = "Djuro",
                            LastName = "Markovic",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            StatusIsActive = true,
                            TwoFactorEnabled = false,
                            UserName = "marko@m7arko.com"
                        },
                        new
                        {
                            Id = 12,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4cf7be92-6443-4328-94c7-f51c39facf9b",
                            Email = "marko@ma7rko.com",
                            EmailConfirmed = true,
                            FirstName = "Ivica",
                            LastName = "Markovic",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            StatusIsActive = true,
                            TwoFactorEnabled = false,
                            UserName = "marko@ma7rko.com"
                        },
                        new
                        {
                            Id = 13,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a56daf66-3b2e-4fc3-9eec-73fd3bfa39c4",
                            Email = "marko@mar7ko.com",
                            EmailConfirmed = true,
                            FirstName = "Marica",
                            LastName = "Markovic",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            StatusIsActive = true,
                            TwoFactorEnabled = false,
                            UserName = "marko@mar7ko.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("UserManagementSystem.Data.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("UserManagementSystem.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("UserManagementSystem.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("UserManagementSystem.Data.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserManagementSystem.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("UserManagementSystem.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserManagementSystem.Data.Models.UserPermission", b =>
                {
                    b.HasOne("UserManagementSystem.Data.Models.Permission", "Permission")
                        .WithMany("Users")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserManagementSystem.Models.User", "User")
                        .WithMany("Permissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserManagementSystem.Data.Models.Permission", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("UserManagementSystem.Models.User", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
