// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserManagementSystem.Data;

namespace UserManagementSystem.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    partial class UsersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("UserManagementSystem.Data.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("UserManagementSystem.Data.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Admin",
                            Description = "Admin opis"
                        },
                        new
                        {
                            Id = 2,
                            Code = "User",
                            Description = "User opsi"
                        });
                });

            modelBuilder.Entity("UserManagementSystem.Data.Models.UserPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersPermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermissionId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            PermissionId = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("UserManagementSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StatusIsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "14aa54f5-7604-41f1-b228-843bad46b407",
                            Email = "marko@marko1.com",
                            EmailConfirmed = true,
                            FirstName = "Administrator",
                            LastName = "Markovic",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            StatusIsActive = true,
                            TwoFactorEnabled = false,
                            UserName = "usernm"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a635760b-8196-48a3-9ec6-3da47e3143a5",
                            Email = "marko@marko2.com",
                            EmailConfirmed = true,
                            FirstName = "Mark",
                            LastName = "Markovic",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            StatusIsActive = true,
                            TwoFactorEnabled = false,
                            UserName = "usernm"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e6a87ea4-327a-46ec-9a72-f6cab5bb86e7",
                            Email = "marko@mar3ko.com",
                            EmailConfirmed = true,
                            FirstName = "Mark",
                            LastName = "Markovic",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            StatusIsActive = true,
                            TwoFactorEnabled = false,
                            UserName = "usernm"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "55a19c49-cd7f-4eaa-97e4-84cb0692a9c4",
                            Email = "marko@mark4o.com",
                            EmailConfirmed = true,
                            FirstName = "Mark",
                            LastName = "Markovic",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            StatusIsActive = true,
                            TwoFactorEnabled = false,
                            UserName = "usernm"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2a0f49a8-f623-489d-b87f-ae91ad1297dd",
                            Email = "marko@marko4.com",
                            EmailConfirmed = true,
                            FirstName = "Mark",
                            LastName = "Markovic",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            StatusIsActive = true,
                            TwoFactorEnabled = false,
                            UserName = "usernm"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7368fc4a-4125-4671-b9a3-2ed179c4d68c",
                            Email = "marko@m6arko.com",
                            EmailConfirmed = true,
                            FirstName = "Mark",
                            LastName = "Markovic",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            StatusIsActive = true,
                            TwoFactorEnabled = false,
                            UserName = "usernm"
                        },
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2f7f12e9-36e6-448b-bf29-5f4762f9cbce",
                            Email = "marko@ma6rko.com",
                            EmailConfirmed = true,
                            FirstName = "Mark",
                            LastName = "Markovic",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            StatusIsActive = true,
                            TwoFactorEnabled = false,
                            UserName = "usernm"
                        },
                        new
                        {
                            Id = 8,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bf9f1d9c-4862-44cd-9cb3-265736a98859",
                            Email = "marko@mar6ko.com",
                            EmailConfirmed = true,
                            FirstName = "Mark",
                            LastName = "Markovic",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            StatusIsActive = true,
                            TwoFactorEnabled = false,
                            UserName = "usernm"
                        },
                        new
                        {
                            Id = 9,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ac1edcdc-b1fe-48f1-bbd4-d77db13f92e5",
                            Email = "marko@mark6o.com",
                            EmailConfirmed = true,
                            FirstName = "Mark",
                            LastName = "Markovic",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            StatusIsActive = true,
                            TwoFactorEnabled = false,
                            UserName = "usernm"
                        },
                        new
                        {
                            Id = 10,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c25b1aea-181a-453a-9458-2469819b5bfa",
                            Email = "marko@marko6.com",
                            EmailConfirmed = true,
                            FirstName = "Mark",
                            LastName = "Markovic",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            StatusIsActive = true,
                            TwoFactorEnabled = false,
                            UserName = "usernm"
                        },
                        new
                        {
                            Id = 11,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "70468c0d-e467-450e-8e8c-f707c07bde2b",
                            Email = "marko@m7arko.com",
                            EmailConfirmed = true,
                            FirstName = "Mark",
                            LastName = "Markovic",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            StatusIsActive = true,
                            TwoFactorEnabled = false,
                            UserName = "usernm"
                        },
                        new
                        {
                            Id = 12,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e6f447ea-5525-4163-871d-d76c9496bed3",
                            Email = "marko@ma7rko.com",
                            EmailConfirmed = true,
                            FirstName = "Mark",
                            LastName = "Markovic",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            StatusIsActive = true,
                            TwoFactorEnabled = false,
                            UserName = "usernm"
                        },
                        new
                        {
                            Id = 13,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7a57ad3e-521b-436c-8774-f871608f9cf3",
                            Email = "marko@mar7ko.com",
                            EmailConfirmed = true,
                            FirstName = "Mark",
                            LastName = "Markovic",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            StatusIsActive = true,
                            TwoFactorEnabled = false,
                            UserName = "usernm"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("UserManagementSystem.Data.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("UserManagementSystem.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("UserManagementSystem.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("UserManagementSystem.Data.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserManagementSystem.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("UserManagementSystem.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserManagementSystem.Data.Models.UserPermission", b =>
                {
                    b.HasOne("UserManagementSystem.Data.Models.Permission", "Permission")
                        .WithMany("Users")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserManagementSystem.Models.User", "User")
                        .WithMany("Permissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserManagementSystem.Data.Models.Permission", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("UserManagementSystem.Models.User", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
